name: Ruscord Node.js CI Linux Build

on:
  workflow_dispatch:

jobs:
  build-debian:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    permissions:
      contents: read

    steps:
      - name: Установить зависимости в контейнер
        run: |
          apt-get update
          apt-get install -y curl git ca-certificates binutils sudo rpm libarchive-tools
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs

      - name: Checkout кода
        uses: actions/checkout@v4

      - name: Установка зависимостей
        run: |
          npm install -g npm@11
          npm ci

      - name: Билд для x64
        run: |
          npx electron-builder --linux --x64 --publish=never

      - name: Загрузка артефактов x64
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-x64
          path: dist/*x64*

      - name: Очистка dist перед ia32
        run: rm -rf dist/*

      - name: Билд для ia32
        run: |
          npx electron-builder --linux --ia32 --publish=never

      - name: Загрузка артефактов ia32
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-ia32
          path: dist/*ia32*
