name: Ruscord Node.js CI Linux Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-debian:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    permissions:
      contents: read

    steps:
      - name: Установить зависимости в контейнер
        run: |
          apt-get update
          apt-get install -y curl git ca-certificates binutils sudo rpm libarchive-tools
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs

      - name: Checkout кода
        uses: actions/checkout@v4

      - name: Обновление библиотек и установка зависимостей с повтором
        run: |
          npm install -g npm@11
          npx npm-check-updates -u
          n=0
          until [ $n -ge 3 ]
          do
            npm install --no-audit --no-fund && break
            n=$((n+1))
            echo "Попытка $n не удалась, пробую снова через 5 секунд..."
            sleep 5
          done
          npm install eslint@latest --save-dev

      - name: Билд файлов
        run: npm run dist

      - name: Загрузка артефактов
        uses: actions/upload-artifact@v4
        with:
          name: ruscord-linux
          path: |
            dist/*.deb
            dist/*.rpm
            dist/*.pacman
            dist/*.AppImage
            dist/*.snap
            dist/*-latest.yml
