name: Ruscord Node.js CI Linux Build

on:
  workflow_dispatch:

jobs:
  build-debian:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    permissions:
      contents: read

    steps:
      - name: Установить зависимости в контейнер
        run: |
          apt-get update
          apt-get install -y curl git ca-certificates binutils sudo rpm libarchive-tools
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs

      - name: Checkout кода
        uses: actions/checkout@v4

      - name: Установка зависимостей
        run: |
          npm install -g npm@11
          npm ci

      # --- Билд для x64 ---
      - name: Билд для x64
        run: |
          npx electron-builder --linux --x64 --publish=never

      - name: Загрузка артефактов x64 (.deb)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-x64-deb
          path: dist/*.deb

      - name: Загрузка артефактов x64 (.rpm)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-x64-rpm
          path: dist/*.rpm

      - name: Загрузка артефактов x64 (.tar.xz)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-x64-tarxz
          path: dist/*.tar.xz

      - name: Загрузка артефактов x64 (.snap)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-x64-snap
          path: dist/*.snap

      - name: Загрузка артефактов x64 (.AppImage)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-x64-appimage
          path: dist/*.AppImage

      - name: Загрузка артефактов x64 (.pacman)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-x64-pacman
          path: dist/*.pacman

      - name: Очистка dist перед ia32
        run: rm -rf dist/*

      # --- Билд для ia32 ---
      - name: Билд для ia32
        run: |
          npx electron-builder --linux --ia32 --publish=never

      - name: Загрузка артефактов ia32 (.deb)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-ia32-deb
          path: dist/*.deb

      - name: Загрузка артефактов ia32 (.rpm)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-ia32-rpm
          path: dist/*.rpm

      - name: Загрузка артефактов ia32 (.tar.xz)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-ia32-tarxz
          path: dist/*.tar.xz

      - name: Загрузка артефактов ia32 (.snap)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-ia32-snap
          path: dist/*.snap

      - name: Загрузка артефактов ia32 (.AppImage)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-ia32-appimage
          path: dist/*.AppImage

      - name: Загрузка артефактов ia32 (.pacman)
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-ia32-pacman
          path: dist/*.pacman
          
