name: Ruscord Node.js CI Linux Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-debian:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    steps:
      - name: Установить зависимости в контейнер
        run: |
          apt-get update
          apt-get install -y curl git ca-certificates binutils sudo rpm bsdtar
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs

      - uses: actions/checkout@v4

      - name: Обновление библиотек до последней версии
        run: npm install -g npm@11 && npx npm-check-updates -u && npm install --no-audit --no-fund && npm install eslint@latest --save-dev

      - name: Билд файлов
        run: npm run dist

      - name: Загрузка артефактов
        uses: actions/upload-artifact@v4
        with:
          name: ruscord-linux
          path: |
            dist/*.deb
            dist/*.rpm
            dist/*.pacman
            dist/*.AppImage
            dist/*.snap
            dist/*-latest.yml
            
