name: Ruscord Node.js CI Linux Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-debian:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    permissions:
      contents: read
    strategy:
      matrix:
        arch: [x64, ia32]

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Установить зависимости в контейнер
        run: |
          apt-get update
          apt-get install -y curl git ca-certificates binutils sudo rpm libarchive-tools
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs

      - name: Checkout кода
        uses: actions/checkout@v4

      - name: Обновление библиотек и установка зависимостей с повтором
        run: |
          npm install -g npm@11
          npx npm-check-updates -u || true
          n=0
          until [ $n -ge 3 ]
          do
            npm install --no-audit --no-fund && break
            n=$((n+1))
            echo "Попытка $n не удалась, запуск снова через 5 секунд..."
            sleep 5
          done
          npm install eslint@latest --save-dev

      - name: Билд файлов для ${{ matrix.arch }}
        run: npx electron-builder --linux --${{ matrix.arch }} --publish=never

      - name: Загрузка .deb
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-${{ matrix.arch }}.deb
          path: dist/*.deb

      - name: Загрузка .rpm
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-${{ matrix.arch }}.rpm
          path: dist/*.rpm

      - name: Загрузка .pacman
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-${{ matrix.arch }}.pacman
          path: dist/*.pacman

      - name: Загрузка .AppImage
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-${{ matrix.arch }}.AppImage
          path: dist/*.AppImage

      - name: Загрузка .snap
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-${{ matrix.arch }}.snap
          path: dist/*.snap

      - name: Загрузка .tar.xz
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-${{ matrix.arch }}.tar.xz
          path: dist/*.tar.xz

      - name: Загрузка -latest.yml
        uses: actions/upload-artifact@v4
        with:
          name: Ruscord-${{ matrix.arch }}-latest-yml
          path: dist/*-latest.yml
